BMW/BMW/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^dealership/', include('dealership.urls', namespace="dealership")),
    url(r'^dealership/', include('dealership.urls', namespace='dealership' , app_name='dealership')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^flagger/', include('flagging.urls', namespace='flagging')),
    url(r'^mobilecheckin/', include('mobilecheckin.urls', namespace='mobilecheckin' , app_name='mobilecheckin')),
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^subview', include('subview.urls')),

# url(r'^oauth2/', include('oauth2_authentication.urls', namespace="oauth2"))
    
)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

BMW/dealership/urls.py
from django.conf.urls import url

from dealership import views

import views.login
import views.chat
from views.overview import *
from views.appointment import *
from views.customers import *
from views.rservices import *
from views.manage import *

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),    
    url(r'^$', views.login.index, name='index'),      
     url(r'delete_models', views.manage.delete_models, name='delete_models'),
    url(r'create_models', views.manage.create_models, name='create_models'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', views.login.loginview, name='login'),  
    url(r'^login/$', views.login.loginview, name='login'),
    url(r'^logout/$', views.login.logoutview, name='logout'),
    url(r'^request/$', views.login.requestview, name='request'),
    url(r'^password/change$', views.login.passchange, name='passchange'),
    url(r'^password/create$', views.login.passcreate, name='passcreate'),
    url(r'^password/reset$', views.login.passreset, name='passreset'),
    url(r'^username/reset$', views.login.userreset, name='userreset'),
    url(r'^terms/$', views.login.terms, name='terms'),
    url(r'^firstlogin/$', views.login.firstlogin, name='firstlogin'),
    #chat
    url(r'^chats/$', views.chat.chats, name='chats'),
    url(r'^chat/$', views.chat.chat, name='chat'),
    #overview
    url(r'^overview/$', views.overview.overview, name='overview'),    
    #url(r'^overview/time/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    url(r'^overview/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    #url(r'^overview/advisor/daily$', views.overview.ov_adv_daily, name='ov_adv_daily'),
    #url(r'^overview/status/daily$', views.overview.ov_status_daily, name='ov_status_daily'),
    #url(r'^overview/time/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    url(r'^overview/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    #url(r'^overview/advisor/weekly$', views.overview.ov_adv_weekly, name='ov_adv_weekly'),
    #url(r'^overview/status/weekly$', views.overview.ov_status_weekly, name='ov_status_weekly'),
    #overview_ajax
    url(r'^overview/wallboard$', views.overview.wallboard_ajax_view, name='wallboard'),
    url(r'^overview/searchcustomer$', views.overview.searchcustomer_ajax_view, name='searchcustomer'),
    url(r'^overview/time/daily/slab$', views.overview.dailyapt_ajax_view, name='ov_time_daily_slab'),
    url(r'^overview/time/daily/search$', views.overview.time_daily_search_ajax_view, name='ov_time_daily_search'),
    url(r'^overview/time/daily/appt$', views.overview.time_daily_search_appt_ajax_view, name='ov_time_daily_search_appt'),
    url(r'^overview/time/daily/row$', views.overview.appointment_row_ajax_view, name='ov_time_daily_row'),
    url(r'^overview/time/weekly/day$', views.overview.time_weekly_day_ajax_view, name='ov_time_weekly_day'),
    url(r'^overview/time/weekly/slab$', views.overview.time_weekly_slab_ajax_view, name='ov_time_weekly_slab'),
    url(r'^overview/daily/advisor$', views.overview.advisor_ajax_view, name='ov_daily_advisor'),
    url(r'^overview/daily/advisor/slab$', views.overview.advisor_daily_slab_ajax_view, name='ov_advisor_daily_slab'),
    url(r'^overview/weekly/advisor/slab$', views.overview.advisor_weekly_slab_ajax_view, name='ov_advisor_weekly_slab'),   
    url(r'^overview/daily/status$', views.overview.status_ajax_view, name='ov_daily_status'),
    url(r'^overview/daily/wayaway$', views.overview.wayaway_ajax_view, name='ov_daily_wayaway'),
    url(r'^overview/daily/status/slab$', views.overview.status_daily_slab_ajax_view, name='ov_status_daily_slab'),
    url(r'^overview/weekly/status/slab$', views.overview.status_weekly_slab_ajax_view, name='ov_status_weekly_slab'),
    url(r'^overview/appointment/detail$', views.overview.appointment_detail_ajax_view, name='ov_appointment_detail'),
    url(r'^overview/update/creaditcard$', views.overview.appointment_update_creditcard, name='ov_update_cc'),
    url(r'^overview/update/vehicle$', views.overview.appointment_update_vehicle, name='ov_update_vehicle'),
    url(r'^overview/update/insurance$', views.overview.appointment_update_insurance, name='ov_update_insurance'),
    #appointment
    url(r'^appointment/$', views.appointment.appointment, name='appointment'),  
    url(r'^appointment/create/update', views.appointment.appointment_create_update, name='appointment_create_update'), 
    url(r'^appointment/customer$', views.appointment.appointment_customer_ajax_view, name='appointment_customer'), 
    url(r'^appointment/customer/vehicle/delete$', views.appointment.customer_delete_vehicle_ajax_view, name='appointment_customer_vehicle_delete'),
    url(r'^appointment/update/time$', views.appointment.appointment_time_ajax_view, name='appointment_update_time'), 
    url(r'^appointment/wayaway$', views.appointment.appointment_wayaway_ajax_view, name='appointment_wayaway'), 
    url(r'^appointment/wayaway/save$', views.appointment.appointment_wayaway_save_ajax, name='appointment_wayaway_save'),
    url(r'^appointment/repair$', views.appointment.appointment_repair_ajax_view, name='appointment_repair'), 
    url(r'^appointment/accountinfo$', views.appointment.appointment_account_info_ajax_view, name='appointment_accountinfo'),
    url(r'^appointment/book', views.appointment.appointment_book_ajax_view, name='appointment_book'),
    url(r'^appointment/remove/service', views.appointment.appointment_remove_service, name='appointment_remove_service'),
    
    #customers
    url(r'^customers/$', views.customers.customers, name='customers'),  
    url(r'^customers/add/user$', views.customers.save_customer_ajax, name='customers_add_user'),
    url(r'^customers/add/vehicle$', views.customers.save_vehicle_ajax, name='customers_add_vehicle'),
    url(r'^customers/add/appointment$', views.customers.save_appointment_ajax, name='customers_add_appointment'),
    url(r'^customers/add/reminder', views.customers.save_guest_reminder_ajax, name='customers_add_reminder'),    
    #repair and servicea
    url(r'^rservices/$', views.rservices.rservices, name='rservices'),
    url(r'^rservices/form$', views.rservices.get_rservices_form, name='rservices_form'),
    url(r'^rservices/create/update', views.rservices.rservices_create_update, name='rservices_create_update'),  
    url(r'^rservices/delete', views.rservices.rservices_delete, name='rservices_delete'),  
    #dealership_manage
    url(r'^manage/$', views.manage.manage, name='manage'),
    url(r'^manage/deatil$', views.manage.details, name='manage_details'),
    url(r'^manage/user_term_advisor$', views.manage.add_user_advisor, name='add_user_advisor'),
    url(r'^manage/add_amenities$', views.manage.add_amenities, name='add_amenities'),
    url(r'^manage/delete_amenities$', views.manage.delete_amenities, name='delete_amenities'),
    url(r'^manage/get_resource_link$', views.manage.get_resource_link, name='get_resource_link'),
    url(r'^manage/add_resource_link$', views.manage.add_resource_link, name='add_resource_link'),
    url(r'^manage/delete_resource_link$', views.manage.delete_resource_link, name='delete_resource_link'),
    url(r'^manage/update_resource_link$', views.manage.update_resource_link, name='update_resource_link'),
    url(r'^manage/get_shopcontacts$', views.manage.get_shopcontacts, name='get_shopcontacts'),
    url(r'^manage/add_shopcontacts$', views.manage.add_shopcontacts, name='add_shopcontacts'),
    url(r'^manage/delete_shopcontacts$', views.manage.delete_shopcontacts, name='delete_shopcontacts'),
    url(r'^manage/update_shopcontacts$', views.manage.update_shopcontacts, name='update_shopcontacts'),
    url(r'^manage/get_marketing$', views.manage.get_marketing, name='get_marketing'),
    url(r'^manage/add_marketing$', views.manage.add_marketing, name='add_marketing'),
    url(r'^manage/get_feedback$', views.manage.get_feedback, name='get_feedback'),
    url(r'^manage/add_feedback$', views.manage.add_feedback, name='add_feedback'),
    url(r'^manage/get_serviceemail$', views.manage.get_serviceemail, name='get_serviceemail'),
    url(r'^manage/add_serviceemail$', views.manage.add_serviceemail, name='add_serviceemail'),
    url(r'^manage/delete_email$', views.manage.delete_email, name='delete_email'),
    url(r'^manage/update_email$', views.manage.update_email, name='update_email'),
    url(r'^manage/get_sms$', views.manage.get_sms, name='get_sms'),
    url(r'^manage/add_sms$', views.manage.add_sms, name='add_sms'),
    url(r'^manage/delete_sms$', views.manage.delete_sms, name='delete_sms'),
    url(r'^manage/update_sms$', views.manage.update_sms, name='update_sms'),
    url(r'^manage/get_shphr$', views.manage.get_shophrs, name='get_shophrs'),
    url(r'^manage/add_shphr$', views.manage.add_shophrs, name='add_shophrs'),
    url(r'^manage/delete_shphr$', views.manage.delete_shophrs, name='delete_shophrs'),
    url(r'^manage/update_shphr$', views.manage.update_shophrs, name='update_shophrs'),
    url(r'^manage/get_holidays$', views.manage.get_holidays, name='get_holidays'),
    url(r'^manage/add_holiday$', views.manage.add_holiday, name='add_holiday'),
    url(r'^manage/delete_holiday$', views.manage.delete_holiday, name='delete_holiday'),
    url(r'^manage/update_holiday$', views.manage.update_holiday, name='update_holiday'),
    url(r'^manage/get_uaform$', views.manage.get_user_advisor_form, name='get_uaform'),
    url(r'^manage/get_editviewuaform$', views.manage.get_edit_view_useradvisor, name='get_editviewuaform'),
    url(r'^manage/edituaform$', views.manage.edit_user_advisor, name='edituaform'),
    url(r'^manage/addteam$', views.manage.add_team, name='add_team'),
    url(r'^manage/editteam$', views.manage.edit_team, name='edit_team'),
    url(r'^manage/addmembers$', views.manage.add_members_team, name='add_team_members'),
    url(r'^manage/deletemembers$', views.manage.delete_members_team, name='delete_team_members'),

BMW/mobilecheckin/urls.py
from django.conf.urls import url

from mobilecheckin.views import login, appointments, overview
from mobilecheckin.views import checkin , walkin , html2canvasproxy


urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),    
    url(r'^$', appointments.index, name='index'),     
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.loginview, name='login'),   
    url(r'^login/$', login.loginview, name='login'),
    url(r'^logout/$', login.logoutview, name='logout'),
    url(r'^request/$', login.requestview, name='request'),
    url(r'^password/change$', login.passchange, name='passchange'),
    url(r'^password/create$', login.passcreate, name='passcreate'),
    url(r'^password/reset$', login.passreset, name='passreset'),
    url(r'^username/reset$', login.userreset, name='userreset'),
    url(r'^firstlogin/$', login.firstlogin, name='firstlogin'),
    url(r'^terms/$', login.terms, name='terms'),
    url(r'^overview/$', overview.overview, name='overview'),    
    #url(r'^overview/time/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    url(r'^overview/daily$', overview.ov_time_daily, name='ov_time_daily'),
    #url(r'^overview/advisor/daily$', views.overview.ov_adv_daily, name='ov_adv_daily'),
    #url(r'^overview/status/daily$', views.overview.ov_status_daily, name='ov_status_daily'),
    #url(r'^overview/time/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    url(r'^overview/weekly$', overview.ov_time_weekly, name='ov_time_weekly'),
    #url(r'^overview/advisor/weekly$', views.overview.ov_adv_weekly, name='ov_adv_weekly'),
    #url(r'^overview/status/weekly$', views.overview.ov_status_weekly, name='ov_status_weekly'),
    #overview_ajax
    url(r'^overview/meters$', overview.meters_ajax_view, name='meters'),
    url(r'^overview/searchcustomer$',overview.searchcustomer_ajax_view, name='searchcustomer'),
    url(r'^overview/time/daily/slab$', overview.dailyapt_ajax_view, name='ov_time_daily_slab'),
    url(r'^overview/time/daily/row$', overview.appointment_row_ajax_view, name='ov_time_daily_row'),
    url(r'^overview/time/weekly/day$', overview.time_weekly_day_ajax_view, name='ov_time_weekly_day'),
    url(r'^overview/time/weekly/slab$', overview.time_weekly_slab_ajax_view, name='ov_time_weekly_slab'),
    url(r'^overview/daily/advisor$', overview.advisor_ajax_view, name='ov_daily_advisor'),
    url(r'^overview/daily/advisor/slab$', overview.advisor_daily_slab_ajax_view, name='ov_advisor_daily_slab'),   
    url(r'^overview/daily/status$', overview.status_ajax_view, name='ov_daily_status'),
     url(r'^overview/daily/status/slab$', overview.status_daily_slab_ajax_view, name='ov_status_daily_slab'),
    url(r'^overview/appointment/detail$', overview.appointment_detail_ajax_view, name='ov_appointment_detail'),
    url(r'^appoinment/update$', appointments.appointment_update, name='appointment_update'),
    url(r'^appoinment/removeservice$', appointments.remove_service, name='remove_service'),
    url(r'^checkin/(?P<appointment_id>\d+)/$', checkin.index, name='checkin'), 
    url(r'^checkin/odometer/(?P<appointment_id>\d+)/$', checkin.get_odo, name='get_odo'),
    url(r'^checkin/servicerepair/(?P<appointment_id>\d+)/$', checkin.get_serviceandrepair, name='get_service_repair'),
    url(r'^checkin/getreview/(?P<appointment_id>\d+)/$', checkin.get_reviewandsign, name='get_review'),
    url(r'^checkin/getodohistory/(?P<appointment_id>\d+)/$', checkin.get_odometer_history, name='get_odo_history'),
    url(r'^checkin/savevin/(?P<appointment_id>\d+)/$', checkin.save_vin, name='save_vin'),
    url(r'^checkin/getservicerepair$', checkin.get_service_repair_list, name='get_service_repair_list'), 
    url(r'^checkin/addservicerepair/(?P<appointment_id>\d+)/$', checkin.add_service_repair, name='add_service_repair'),
    url(r'^checkin/update_service_repair/(?P<appointment_id>\d+)/$', checkin.update_service_repair, name='update_service_repair'),
    
    url(r'^checkin/removeservicerepair/(?P<appointment_id>\d+)/$', checkin.remove_service_repair, name='remove_service_repair'),
    url(r'^checkin/getbynameservicerepair$', checkin.get_by_name_service_repair, name='get_by_name_service_repair'), 
    url(r'^checkin/getwalkaround/(?P<appointment_id>\d+)/$', checkin.get_walkaround, name='get_walkaround'),
    url(r'^checkin/addwalkaroundnotes/(?P<appointment_id>\d+)/$', checkin.add_notes_walkaround, name='add_walkaround_notes'),
    url(r'^checkin/getwalkaroundmedia/(?P<appointment_id>\d+)/$', checkin.get_walkaround_media, name='get_walkaround_media'),
    url(r'^checkin/getwalkaroundnotes/(?P<appointment_id>\d+)/$', checkin.get_walkaround_notes, name='get_walkaround_notes'),
    url(r'^checkin/getselectedvehicledetails$', checkin.get_selected_vehicle, name='get_selected_vehicle'), 
    url(r'^checkin/addinitials/(?P<appointment_id>\d+)/$', checkin.add_walkaround_initials, name='add_initials'),
    url(r'^checkin/acceptappointment/(?P<appointment_id>\d+)/$', checkin.accept_appointment_summary, name='accept_appointment'),
    url(r'^checkin/cancelappointment/(?P<appointment_id>\d+)/$', checkin.cancle_appointment_summary, name='cancel_appointment'),
    url(r'^walkinappointmet/$', walkin.create_appointment, name='walkin_appointment'),
    url(r'^walkinsearchcustomer/$', walkin.searchuser, name='walkin_search'),
    url(r'^image_proxy/$', html2canvasproxy.imgProxy, name='image_proxy'),
    url(r'^checkin/getselectedvehiclemap$', checkin.get_selected_vehicle_map, name='get_selected_vehicle_map'), 
    url(r'^checkin/get_tire_thread/(?P<appointment_id>\d+)/$', checkin.get_tire_thread, name='get_tire_thread'),
    url(r'^checkin/add_appointment_notes/(?P<appointment_id>\d+)/$', checkin.add_tire_notes, name='add_tire_notes'),
    url(r'^checkin/pdf/(?P<appointment_id>\d+)/$', checkin.pfd_view, name='pdf_view'),
]

BMW/mobilecheckin/templates/mobilecheckin/base.html
{% load dealership_detail %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>{%dealer_title dealer_code%}</title>
{% load staticfiles %}
<!-- Bootstrap core CSS -->
<link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="{% static "css/mobilecheckin.css" %}" rel="stylesheet">
<link href="{% static "css/mbcamera.css" %}" rel="stylesheet">
<link href="{% static "lightbox/css/lightbox.css" %}" rel="stylesheet">
<link href="{% static "css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet">
<link href="{% static "css/bootstrap-timepicker.min.css" %}" rel="stylesheet">
<link href="{% static "css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet">
<link href="{% static "css/datepicker.css" %}" rel="stylesheet">
<script src="{% static "js/jquery-1.10.2.min.js" %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>
<!-- centrifuge js file -->
<script src="{% static "js/puller.js" %}"></script>
<script src="{% static "js/centrifuge.js" %}"></script>
<script src="{% static "js/sock.js" %}"></script>
<script src="{% static "js/sha.js" %}"></script>
<link  href="{% static "customer/cropper/cropper.css" %}" rel="stylesheet">
<script src="{% static "customer/cropper/cropper.js" %}"></script>
<script src="{% static "customer/js/utility.js" %}"></script>
<script src="https://web.archive.org/web/20140814064901/http://www.nihilogic.dk/labs/exif/exif.js"></script>
<script src="https://web.archive.org/web/20140814064903/http://www.nihilogic.dk/labs/binaryajax/binaryajax.js"></script>

			
<!-- centrifuge js file -->
<!-- Just for debugging purposes. Don't actually copy this line! -->
<!--[if lt IE 9]><script src="js/ie8-responsive-file-warning.js"></script><![endif]-->

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" href="{% static "css/font-awesome.css" %}" />
<link rel="shortcut icon" href="{% static "images/favicon.png" %}" />
</head>
<body>
{% block header %}
<header>
	<div class="page-header">
        <div class="container-fluid">
        	<div class="row">
            	<div class="col-lg-12">
                	<div class="col-xs-6">
                	<a href="#" class="logo"><h1>{%dealer_detail dealer_code%} MOBILE CHECK-IN</h1></a>
                    
                </div>
                     	<div class="col-xs-6 mt-10">
                			<div class="pull-right">
                			<span class="login text_wht">
                            {% if user.is_authenticated %}
                            	Welcome <a href="#" class="text_wht">{{user}}</a><a href="{% url 'mobilecheckin:logout' %}" class="ml-10 btn btn-sm btn-danger">Log Out</a>
                            {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>		
    </div>
</header>
{% endblock %}
<div id="loading_page">
	<img id="loading-image-page" src="{% static "customer/images/ajax-loader.gif" %}" alt="Loading..." />
</div>
<div class="clear"></div>
{% block main %}
{% endblock%}

{% block js %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script src="{% static "js/moment.min.js" %}"></script>
<script src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
<script src="{% static "js/dealership.js" %}"></script>
<script src="{% static "js/dealership_overview.js" %}"></script>
<script src="{% static "js/dealership_appointment.js" %}"></script>
<script src="{% static "customer/js/vehicle_selection.js" %}"></script>
<script src="{% static "customer/js/snapshot.js" %}"></script>
<script src="{% static "customer/js/bootstrap_dialog.js" %}"></script>
<script>
var url_ov_time_daily_slab = "{% url 'dealership:ov_time_daily_slab' %}";
var url_ov_time_weekly_day = "{% url 'mobilecheckin:ov_time_weekly_day' %}";
var url_ov_time_weekly_slab = "{% url 'mobilecheckin:ov_time_weekly_slab' %}";
var url_ov_appointment_detail = "{% url 'dealership:ov_appointment_detail' %}";
var url_ov_advisor = "{% url 'mobilecheckin:ov_daily_advisor' %}";
var url_ov_status = "{% url 'mobilecheckin:ov_daily_status' %}";
var url_ov_advisor_daily_slab = "{% url 'mobilecheckin:ov_advisor_daily_slab' %}";
var url_ov_status_daily_slab = "{% url 'mobilecheckin:ov_status_daily_slab' %}";
var url_appointment_update = "{% url 'mobilecheckin:appointment_update' %}";
var url_remove_service = "{% url 'mobilecheckin:remove_service' %}";
var url_ov_time_daily_search = "{% url 'dealership:ov_time_daily_search' %}";
</script>
{% endblock%}
{% block extra %}
{% endblock%}
</body>
</html>

BMW/mobilecheckin/templates/mobilecheckin/messages.html
<div class="successbox">Successful operation message</div>
<div class="errorbox">Error: Opps Something Went Wrong</div>