BMW/BMW/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^dealership/', include('dealership.urls', namespace="dealership")),
    url(r'^dealership/', include('dealership.urls', namespace='dealership' , app_name='dealership')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^flagger/', include('flagging.urls', namespace='flagging')),
    url(r'^mobilecheckin/', include('mobilecheckin.urls', namespace='mobilecheckin' , app_name='mobilecheckin')),
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^subview', include('subview.urls')),

# url(r'^oauth2/', include('oauth2_authentication.urls', namespace="oauth2"))
    
)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

BMW/mobilecheckin/urls.py
from django.conf.urls import url

from mobilecheckin.views import login, appointments, overview
from mobilecheckin.views import checkin , walkin , html2canvasproxy


urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),    
    url(r'^$', appointments.index, name='index'),     
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.loginview, name='login'),   
    url(r'^login/$', login.loginview, name='login'),
    url(r'^logout/$', login.logoutview, name='logout'),
    url(r'^request/$', login.requestview, name='request'),
    url(r'^password/change$', login.passchange, name='passchange'),
    url(r'^password/create$', login.passcreate, name='passcreate'),
    url(r'^password/reset$', login.passreset, name='passreset'),
    url(r'^username/reset$', login.userreset, name='userreset'),
    url(r'^firstlogin/$', login.firstlogin, name='firstlogin'),
    url(r'^terms/$', login.terms, name='terms'),
    url(r'^overview/$', overview.overview, name='overview'),    
    #url(r'^overview/time/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    url(r'^overview/daily$', overview.ov_time_daily, name='ov_time_daily'),
    #url(r'^overview/advisor/daily$', views.overview.ov_adv_daily, name='ov_adv_daily'),
    #url(r'^overview/status/daily$', views.overview.ov_status_daily, name='ov_status_daily'),
    #url(r'^overview/time/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    url(r'^overview/weekly$', overview.ov_time_weekly, name='ov_time_weekly'),
    #url(r'^overview/advisor/weekly$', views.overview.ov_adv_weekly, name='ov_adv_weekly'),
    #url(r'^overview/status/weekly$', views.overview.ov_status_weekly, name='ov_status_weekly'),
    #overview_ajax
    url(r'^overview/meters$', overview.meters_ajax_view, name='meters'),
    url(r'^overview/searchcustomer$',overview.searchcustomer_ajax_view, name='searchcustomer'),
    url(r'^overview/time/daily/slab$', overview.dailyapt_ajax_view, name='ov_time_daily_slab'),
    url(r'^overview/time/daily/row$', overview.appointment_row_ajax_view, name='ov_time_daily_row'),
    url(r'^overview/time/weekly/day$', overview.time_weekly_day_ajax_view, name='ov_time_weekly_day'),
    url(r'^overview/time/weekly/slab$', overview.time_weekly_slab_ajax_view, name='ov_time_weekly_slab'),
    url(r'^overview/daily/advisor$', overview.advisor_ajax_view, name='ov_daily_advisor'),
    url(r'^overview/daily/advisor/slab$', overview.advisor_daily_slab_ajax_view, name='ov_advisor_daily_slab'),   
    url(r'^overview/daily/status$', overview.status_ajax_view, name='ov_daily_status'),
     url(r'^overview/daily/status/slab$', overview.status_daily_slab_ajax_view, name='ov_status_daily_slab'),
    url(r'^overview/appointment/detail$', overview.appointment_detail_ajax_view, name='ov_appointment_detail'),
    url(r'^appoinment/update$', appointments.appointment_update, name='appointment_update'),
    url(r'^appoinment/removeservice$', appointments.remove_service, name='remove_service'),
    url(r'^checkin/(?P<appointment_id>\d+)/$', checkin.index, name='checkin'), 
    url(r'^checkin/odometer/(?P<appointment_id>\d+)/$', checkin.get_odo, name='get_odo'),
    url(r'^checkin/servicerepair/(?P<appointment_id>\d+)/$', checkin.get_serviceandrepair, name='get_service_repair'),
    url(r'^checkin/getreview/(?P<appointment_id>\d+)/$', checkin.get_reviewandsign, name='get_review'),
    url(r'^checkin/getodohistory/(?P<appointment_id>\d+)/$', checkin.get_odometer_history, name='get_odo_history'),
    url(r'^checkin/savevin/(?P<appointment_id>\d+)/$', checkin.save_vin, name='save_vin'),
    url(r'^checkin/getservicerepair$', checkin.get_service_repair_list, name='get_service_repair_list'), 
    url(r'^checkin/addservicerepair/(?P<appointment_id>\d+)/$', checkin.add_service_repair, name='add_service_repair'),
    url(r'^checkin/update_service_repair/(?P<appointment_id>\d+)/$', checkin.update_service_repair, name='update_service_repair'),
    
    url(r'^checkin/removeservicerepair/(?P<appointment_id>\d+)/$', checkin.remove_service_repair, name='remove_service_repair'),
    url(r'^checkin/getbynameservicerepair$', checkin.get_by_name_service_repair, name='get_by_name_service_repair'), 
    url(r'^checkin/getwalkaround/(?P<appointment_id>\d+)/$', checkin.get_walkaround, name='get_walkaround'),
    url(r'^checkin/addwalkaroundnotes/(?P<appointment_id>\d+)/$', checkin.add_notes_walkaround, name='add_walkaround_notes'),
    url(r'^checkin/getwalkaroundmedia/(?P<appointment_id>\d+)/$', checkin.get_walkaround_media, name='get_walkaround_media'),
    url(r'^checkin/getwalkaroundnotes/(?P<appointment_id>\d+)/$', checkin.get_walkaround_notes, name='get_walkaround_notes'),
    url(r'^checkin/getselectedvehicledetails$', checkin.get_selected_vehicle, name='get_selected_vehicle'), 
    url(r'^checkin/addinitials/(?P<appointment_id>\d+)/$', checkin.add_walkaround_initials, name='add_initials'),
    url(r'^checkin/acceptappointment/(?P<appointment_id>\d+)/$', checkin.accept_appointment_summary, name='accept_appointment'),
    url(r'^checkin/cancelappointment/(?P<appointment_id>\d+)/$', checkin.cancle_appointment_summary, name='cancel_appointment'),
    url(r'^walkinappointmet/$', walkin.create_appointment, name='walkin_appointment'),
    url(r'^walkinsearchcustomer/$', walkin.searchuser, name='walkin_search'),
    url(r'^image_proxy/$', html2canvasproxy.imgProxy, name='image_proxy'),
    url(r'^checkin/getselectedvehiclemap$', checkin.get_selected_vehicle_map, name='get_selected_vehicle_map'), 
    url(r'^checkin/get_tire_thread/(?P<appointment_id>\d+)/$', checkin.get_tire_thread, name='get_tire_thread'),
    url(r'^checkin/add_appointment_notes/(?P<appointment_id>\d+)/$', checkin.add_tire_notes, name='add_tire_notes'),
    url(r'^checkin/pdf/(?P<appointment_id>\d+)/$', checkin.pfd_view, name='pdf_view'),
]

BMW/customer/views/login.py
# Create your views here.
'''Login for Customers'''

from datetime import date, timedelta
import json
import os

from django.conf import settings
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import get_user_model
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.models import get_current_site
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse
from django.http import HttpResponseBadRequest, request
from django.http import HttpResponseRedirect
from django.http import HttpResponseRedirect
from django.http.response import Http404, JsonResponse
from django.shortcuts import render
from django.shortcuts import render
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.timezone import get_current_timezone
from googleapiclient import discovery
import httplib2
from oauth2client.client import flow_from_clientsecrets
from oauth2client.contrib import xsrfutil
from oauth2client.contrib.django_orm import Storage

from BMW import settings
from apiclient.discovery import build
from customer.app_confg import confg
from customer.decorators.decorators import customer_group_check, dealership_required
from customer.factories import CustomerServicesFactory
from customer.forms import CustomerVehichleForm, ImageUploadForm
# from customer.models import CredentialsModel, FlowModel
from customer.services.google import GoogleService
from customer.services.importservice import ImportContact
from customer.services.userservices import CUserService
from dealership.factories import DealerShipServicesFactory
from dealership.forms import *
from dealership.models import VinYear
import json as mainjson
from livechat.forms import UploadForm
from livechat.models import Upload
from string import lower


def auth_return(request):
#     user = request.user
    if request.session.get("oauth_appointment"):
        customer_factory = CustomerServicesFactory()
        dealer_factory = DealerShipServicesFactory()
        dealer_service = dealer_factory.get_instance("dealership")
        appt_service = dealer_factory.get_instance("appointment") #AppointmentService()
        appointment  =appt_service.get_appointment(request.session.get("oauth_appointment"))#,dealer)
#         if not xsrfutil.validate_token(
#                 settings.SECRET_KEY, request.REQUEST['state'], user):
#             return HttpResponseBadRequest()
        FLOW = FlowModel.objects.get(id=appointment).flow
        credential = FLOW.step2_exchange(request.REQUEST)
        storage = Storage(CredentialsModel, 'id', appointment, 'credential')
        storage.put(credential)
        return HttpResponseRedirect(reverse('customer:sync_gcalendar')+"?appointment_id="+str(appointment.id))
    



def import_csv(request):
    imprt = ImportContact()
    row = [""] * 100 
    row[1] = "test"
    row[2] = "user"
    row[3] = "test.user@gmail.com"
    row[4] = "(1231)1231-1231"
    row[5] = "(1231)1231-1231"
    
    row[6] = "US"
    row[7] = "House # 4151 st #10"
    row[8] = " California"
    row[9] = "CA"
    row[10] = "1231"
    row[18] = "2007"
    row[19] = "Infiniti"
    row[20] = "Q3"
    row[26] = "123131"
    row[28] = "Black"
    row[29] = 1110
    row[33] = "11/04/2015 01:16 PM"
    row[34] = "11/04/2015 01:16 PM"
    row[35] = "Rachel Blach"
    row[41] = "Oil change"
    row[44] = 100
    row[45] = "completed"
#     imprt.add_row(row)
    imprt.import_file()
    
    
def sync_gcalendar(request):
    gcalservice = GoogleService()
    if request.GET.get("appointment_id"):
        if request.GET.get("refferrer"):
            request.session["refferrer"] =request.GET.get("refferrer") 
        
        customer_factory = CustomerServicesFactory()
        dealer_factory = DealerShipServicesFactory()
        dealer_service = dealer_factory.get_instance("dealership")
#         dealer = dealer_service.get_dealer_by(dealer_code)
        uservice = customer_factory.get_instance("user") #CUserService()
        appt_service = dealer_factory.get_instance("appointment") #AppointmentService()
        appointment  =appt_service.get_appointment(request.GET.get("appointment_id"))#,dealer)

#         REDIRECT_URI = 'http://127.0.0.1:8000/customer/oauth2callback/'#?appointment_id='+request.GET.get("appointment_id")
        request.session["oauth_appointment"]  =request.GET.get("appointment_id")
        #REDIRECT_URI = "https://%s%s" % (
        #   get_current_site(request).domain, reverse("customer:return"))
        REDIRECT_URI = settings.SITE_MAIN_URL+reverse("customer:return")
        CLIENT_SECRETS = os.path.join(
        os.path.dirname(__file__), gcalservice.CLIENT_SECRET_FILE)
        
        FLOW = flow_from_clientsecrets(
            CLIENT_SECRETS,
            scope=gcalservice.SCOPES,
            redirect_uri=REDIRECT_URI
        )
        storage = Storage(CredentialsModel, 'id', appointment, 'credential')
        credential = storage.get()
        if credential is None or credential.invalid is True:
            FLOW.params['state'] = xsrfutil.generate_token(
                settings.SECRET_KEY, appointment)
            authorize_url = FLOW.step1_get_authorize_url()
            f = FlowModel(id=appointment, flow=FLOW)
            f.save()
            
            return HttpResponseRedirect(authorize_url)
        else:
            resp = gcalservice.create_event(appointment,credential)
            messages.success(request, "Your appointment has been added to Google Calendars")
            if request.session.get("refferrer"):
                refferrer =request.session["refferrer"]
                del request.session["refferrer"]
                return HttpResponseRedirect(refferrer)
            else:
            
                return JsonResponse({"success":resp},safe=False) 
            
            
@dealership_required
def testing(request,dealer_code=None):
    customer_factory = CustomerServicesFactory()
    dealer_factory = DealerShipServicesFactory()
    
    dealer_service = dealer_factory.get_instance("dealership")#DealerShipService()
    dealership = dealer_service.get_dealer_by(request.session.get("dealer_code")) 
    capacityservice = dealer_factory.get_instance("capacity")
#     slab_time = timezone.now() - timedelta(hours=44)
    slab_time = datetime.datetime.strptime('Jan 29 2016  9:20AM', '%b %d %Y %I:%M%p')
    slab_time = timezone.make_aware(slab_time)
    print slab_time
    capacity = capacityservice.check_slab_availibity(slab_time,dealership)
    print capacity
#   


def pull_models(request):
    dealer_id = 1
    year = 2017
    models = ["230i Convertible","230i Coupe","230i xDrive Convertible","230i xDrive Coupe","320i Sedan","320i xDrive Sedan","328d Sedan","328d xDrive Sedan","328d xDrive Wagon","330e iPerformance","330i Sedan","330i xDrive Gran Turismo","330i xDrive Sedan","330i xDrive Wagon","340i Sedan","340i xDrive Gran Turismo","340i xDrive Sedan","430i Convertible","430i Coupe","430i Gran Coupe","430i xDrive Convertible","430i xDrive Coupe","430i xDrive Gran Coupe","440i Convertible","440i Coupe","440i Gran Coupe","440i xDrive Convertible","440i xDrive Coupe","440i xDrive Gran Coupe","530i Sedan","530i xDrive Sedan","535i Gran Turismo","535i xDrive Gran Turismo","540i Sedan","540i xDrive Sedan","550i xDrive Gran Turismo","640i Convertible","640i Coupe","640i Gran Coupe","640i xDrive Convertible","640i xDrive Coupe","640i xDrive Gran Coupe","740i Sedan","740i xDrive Sedan","750i Sedan","750i xDrive Sedan","ALPINA B6 xDrive Gran Coupe","ALPINA B7 xDrive","M2","M240i Convertible","M240i Coupe","M240i xDrive Convertible","M240i xDrive Coupe","M3 Sedan","M4 Convertible","M4 Coupe","M6 Convertible","M6 Coupe","M6 Gran Coupe","M760i xDrive Sedan","X1 sDrive28i","X1 xDrive28i","X3 sDrive28i","X3 xDrive28d","X3 xDrive28i","X3 xDrive35i","X4 M40i","X4 xDrive28i","X5 M","X5 sDrive35i","X5 xDrive35i","X5 xDrive40e","X5 xDrive50i","X6 M","X6 sDrive35i","X6 xDrive35i","X6 xDrive50i","i3","i3 (60 ah)","i3 with Range Extender","i8"]
    make_id = 2
    for model in models:
        try:
            m = VinModel.objects.get(name=model)
        except Exception,e:
            m = VinModel(name=model,val=model)
            m.save()
        try:
            y = VinYear.objects.get(name=year)
        except Exception,e:
            y = VinYear(name=year,val=year)
            y.save()
        try:
            vehicle = Vehicle.objects.get(model=m,year=y,make_id=make_id)
        except Exception,e:
            vehicle = Vehicle(model=m,year=y,make_id=make_id)
            vehicle.mainimage = model.lower()+".jpg"
            vehicle.save()
#         image = get_image(model,year)
#         if image:
#             vehicle.mainimage = 
        try:
            dealer_vehicle = DealersVehicle.objects.get(vehicle=vehicle,dealer_id=dealer_id)
        except Exception,e:
            dealer_vehicle = DealersVehicle(vehicle=vehicle,dealer_id=dealer_id)
            dealer_vehicle.save()
    return JsonResponse({"success":True},safe=False) 
def get_image(model,year):
    url = "https://www.googleapis.com/customsearch/v1?key=AIzaSyAbVHjVJZHFh6jQZkh1XkhQ-e-gCTQ1rOA&cx=009864217067913918543:rlma41jwnds&q="+model+" "+year
    js = json.loads(url)




@dealership_required  
def delete_models(request,dealer_code=None):
  
            
    if dealer_code:
        year = 1998
        if request.GET.get("year")!=None:
            year = request.GET.get("year")
           
        if request.POST.get("models")!=None:
            models = request.POST.getlist("models")
#             delete_vehicle = DealersVehicle.objects.filter(vehicle__year__name = year)
            delete_vehicle = DealersVehicle.objects.filter(id__in=models)
            delete_vehicle.delete()

BMW/mobilecheckin/templates/mobilecheckin/login/firstlogin.html
{% extends 'mobilecheckin/login/password_base.html' %}
{% block title %}
<h3 class="font_regular">Create New Password</h3>
{% endblock %}  

{% block fields %}    			 
<div class="col-sm-9">
<p>Please enter a new password that you will remember. The password must be atleast sex characters. With atleast one uper case character, one lower case charecter, one number and one sumble.</p>

	<form id="form_pass" action="{% url 'mobilecheckin:firstlogin' %}" method="post">  
		{% csrf_token %}
	    <div class="form-group">
	    	{{ form.new }}
	        <!-- <input type="password" class="form-control" id="new" placeholder="Enter New Password"> -->
	    </div>
	    <div class="form-group">
	    	{{ form.confirm }}
	        <!-- <input type="password" class="form-control" id="confirm" placeholder="Confirm Password"> -->
	    </div>
	    <div class="form-group">
	    	{{ form.questions }}
	        <!-- <input type="password" class="form-control" id="confirm" placeholder="Confirm Password"> -->
	    </div>
	      <div class="form-group">
	    	{{ form.answer }}
	        <!-- <input type="password" class="form-control" id="confirm" placeholder="Confirm Password"> -->
	    </div>
	    <div class="clear pad-5"></div>

	    <button type="submit" class="btn btn-info">Ok</button> &nbsp; 
	    

	</form>

</div>
{% endblock %} 

BMW/mobilecheckin/templates/mobilecheckin/login/login.html
{% extends 'mobilecheckin/base.html' %}
{% block main %}
<div class="clear pad-50"></div>
<div class="container-fluid">
	<div class="row">
    	<div class="col-sm-offset-3 col-sm-6">
            <div class="LoginBox">
            	<h3 class="mt-0 text-center">Login to Mobile Checkin</h3>
                <hr>
               	{% if  form.non_field_errors %}
		                <div class="alert error alert-danger fade in">
					    	<a href="#" class="close" data-dismiss="alert">&times;</a>
					    	<strong>Error!</strong>{{ form.non_field_errors }}
						</div>
               		 
                {%endif%}
               
                <form action="{% url 'mobilecheckin:login' %}" method="post">
                <input type="hidden" name="dealer_code" value="{{code}}" />
                	{% csrf_token %}
                	<div class="form-group">
                    	<!--  <input type="text" class="form-control" id="" name="username" placeholder="Username">-->
                    		{% if  form.username.errors %}
                    	 <div class="alert error alert-danger fade in">
					    	<a href="#" class="close" data-dismiss="alert">&times;</a>
					    	<strong>Error!</strong>{{ form.username.errors }}
						</div>
						{%endif%}
                    	{{ form.username }}
                        <p class="text-right"><small><a href="{% url 'mobilecheckin:userreset' %}?dealer_code={{code}}">Forgot Username?</a></small></p>
  					</div>
  					<div class="form-group">
                    	<!--  <input type="password" class="form-control" id="" name="password" placeholder="Password">-->
                    	{{ form.password }}
                        <p class="text-right"><small><a href="{% url 'mobilecheckin:passreset' %}?dealer_code={{code}}">Forgot Password?</a></small></p>
  					</div>
                    <div class="checkbox">
                    	<label class="mr-30">
                    		{{ form.remember }} Keep me logged in
                    		<!--
                        	<input type="checkbox"> Keep me logged in
                        	-->
                        </label>
                        <a href="{% url 'mobilecheckin:request' %}?dealer_code={{dealer_code}}" class="font_regular NewUserTxt">I am a new user</a>
                    </div>
                    <div class="clear pad-5"></div>
                    <button type="submit" class="btn btn-info">Submit</button>
				</form>
            </div>
        </div>
    </div>
</div>
<div class="clear pad-5"></div>
{% endblock %}

BMW/mobilecheckin/templates/mobilecheckin/login/password_change.html
{% extends 'mobilecheckin/login/password_base.html' %}
{% block title %}
<h3 class="font_regular">Change Password</h3>  
{% endblock %}  

{% block fields %}    			 
<div class="col-sm-9">
	<p>Please enter a new password that you will remember. The password must be atleast six characters. With atleast one uper case character, one lower case charecter, one number and one symbol.</p>
    
    <form id="form_pass" action="{% url 'dealership:passchange' %}" method="post">
    	{% csrf_token %}
    	<div class="form-group">
    		{% if  form.current.errors %}
	        	 <div class="alert error alert-danger fade in">
			    	<a href="#" class="close" data-dismiss="alert">&times;</a>
			    	<strong>Error!</strong>{{ form.current.errors }}
				</div>
			{%endif%}
    		{{ form.current }}
            <!-- <input type="password" class="form-control" id="current" placeholder="Enter Current Password"> -->
        </div>
        <div class="form-group">
        	{{ form.new }}
            <!-- <input type="password" class="form-control" id="new" placeholder="Enter New Password"> -->
        </div>
        <div class="form-group">
        	{{ form.confirm }}
            <!-- <input type="password" class="form-control" id="confirm" placeholder="Confirm Password"> -->
        </div>
        <div class="clear pad-5"></div>
        <button type="submit" class="btn btn-info" id="submit">Ok</button>
        <a href="{% url 'dealership:index'?dealer_code={{code}} %}" class="btn btn-grey">Cancel</a>
    </form>    
</div>
{% endblock %} 

BMW/mobilecheckin/templates/mobilecheckin/login/password_reset.html
{% extends 'mobilecheckin/base.html' %}
{% block main %}
<div class="clear pad-50"></div>
<div class="container-fluid">
	<div class="row">
    	<div class="col-sm-offset-3 col-sm-6">
            <div class="LoginBox">
            	<h3 class="mt-0 text-center">Reset Password</h3>
                <p>Please enter the email associated with your Dealership account and we will send instructions.</p>
                <form action="{% url 'mobilecheckin:passreset' %}" method="post"> 
                	{% csrf_token %}
                	<div class="form-group">
                		{% if  form.email.errors %}
				        	 <div class="alert error alert-danger fade in">
						    	<a href="#" class="close" data-dismiss="alert">&times;</a>
						    	<strong>Error!</strong>{{ form.email.errors }}
							</div>
						{%endif%}
                		{{ form.email }}
                    	<!-- <input type="email" class="form-control" id="" placeholder="c"> -->
  					</div>  					
                    <div class="clear pad-5"></div>
                    <button type="submit" class="btn btn-info">Ok</button> &nbsp; 
                    <a href="{% url 'dealership:login' %}?dealer_code={{code}}" class="btn btn-default">Cancel</a>
				</form>
            </div>
        </div>
    </div>
</div>
<div class="clear pad-5"></div>
{% endblock %}

BMW/mobilecheckin/templates/mobilecheckin/login/request.html
{% extends 'mobilecheckin/base.html' %}
{% block main %}
<div class="clear pad-50"></div>
<div class="container-fluid">
	<div class="row">
    	<div class="col-sm-offset-3 col-sm-6">
            <div class="LoginBox">
            	<h3 class="mt-0 text-center">Account Request</h3>
                <p>Please enter email id that you want to use for registration</p>
                <form action="{% url 'mobilecheckin:request' %}" method="post"> 
                	{% csrf_token %}
                	<div class="form-group">
                		{% if  form.email.errors %}
				        	 <div class="alert error alert-danger fade in">
						    	<a href="#" class="close" data-dismiss="alert">&times;</a>
						    	<strong>Error!</strong>{{ form.email.errors }}
							</div>
						{%endif%}
                		{{ form.email }}
                    	<!-- <input type="email" class="form-control" id="" placeholder="c"> -->
  					</div>  					
                    <div class="clear pad-5"></div>
                    <button type="submit" class="btn btn-info">Ok</button> &nbsp; 
                    <a href="{% url 'mobilecheckin:login' %}?dealer_code={{code}}" class="btn btn-grey">Cancel</a>
				</form>
            </div>
        </div>
    </div>
</div>
<div class="clear pad-5"></div>
{% endblock %}

BMW/mobilecheckin/templates/mobilecheckin/login/username_reset.html
{% extends 'mobilecheckin/base.html' %}
{% block main %}
<div class="clear pad-50"></div>
<div class="container-fluid">
	<div class="row">
    	<div class="col-sm-offset-3 col-sm-6">
            <div class="LoginBox">
            	<h3 class="mt-0 text-center">Retrieve Username</h3>
                <p>Please enter the email associated with your Dealership account and we will send instructions.</p>
                <form action="{% url 'mobilecheckin:userreset' %}" method="post"> 
                	{% csrf_token %}
                	<div class="form-group">
                		{% if  form.email.errors %}
				        	 <div class="alert error alert-danger fade in">
						    	<a href="#" class="close" data-dismiss="alert">&times;</a>
						    	<strong>Error!</strong>{{ form.email.errors }}
							</div>
						{%endif%}
                		{{ form.email }}
                    	<!-- <input type="email" class="form-control" id="" placeholder="c"> -->
  					</div>  					
                    <div class="clear pad-5"></div>
                    <button type="submit" class="btn btn-info">Ok</button> &nbsp; 
                    <a href="{% url 'mobilecheckin:login' %}?dealer_code={{code}}" class="btn btn-default">Cancel</a>
				</form>
            </div>
        </div>
    </div>
</div>
<div class="clear pad-5"></div>
{% endblock %}