BMW/BMW/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^dealership/', include('dealership.urls', namespace="dealership")),
    url(r'^dealership/', include('dealership.urls', namespace='dealership' , app_name='dealership')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^flagger/', include('flagging.urls', namespace='flagging')),
    url(r'^mobilecheckin/', include('mobilecheckin.urls', namespace='mobilecheckin' , app_name='mobilecheckin')),
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^subview', include('subview.urls')),

# url(r'^oauth2/', include('oauth2_authentication.urls', namespace="oauth2"))
    
)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

BMW/customer/urls.py
from django.conf.urls import url

from customer.views import login, main, vehicle, account, notifications, appoint, service , statusalert,cart


urlpatterns = [  
    url(r'^$', login.login, name='index'),
#     url(r'^import_csv$', login.import_csv, name='index'),
    url(r'pull_models', login.pull_models, name='pull_models'),
    url(r'create_models', login.create_models, name='create_models'),
    url(r'delete_models', login.delete_models, name='delete_models'),
    url(r'create_models', login.create_models, name='create_models'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.login, name='login'),
    url(r'^login/?$', login.login, name='login'),
    url(r'^password/reset/$', login.passreset, name='passreset'),
    url(r'^username/reset/$', login.userreset, name='userreset'),
    url(r'^password/create$', login.passcreate, name='passcreate'),
    url(r'^main/$', vehicle.mainview , name='main'),
    url(r'^accountsettings/$', account.accountview , name='accountsettings'),
    url(r'^logout/$', login.logout, name='logout'),
    url(r'^test_ocr/$', main.test_ocr, name='test_ocr'),
    url(r'^puller/$', main.test_puller, name='puller'),
    url(r'^vehichlewidget/$', vehicle.get_vehicle, name='vehichlewidget'),
    url(r'^delete_vehicle/$', vehicle.del_vehicle, name='del_vehicle'),
    url(r'^ocr_snap/$', vehicle.ocr_snap, name='ocr_snap'),
    url(r'^delete_account/$', account.delete, name='delete_account'),
    url(r'^notifications/$', notifications.notificationssettings, name='notifications'),
    url(r'^findapp/$', appoint.find_exiting_appointment, name='findapp'),
    url(r'^search_app/$', appoint.search_app, name='search_app'),#used for searching thourhg ajax
    url(r'^new_customer_vehicle/$', login.new_customer_vehicle, name='new_customer_vehicle'),
    url(r'^vehicle_selection_appointment/$', appoint.vehicle_selection, name='vehicle_selection_appointment'),
    url(r'^service_selection_appointment/$', appoint.service_selection_appointment, name='service_selection_appointment'),
    url(r'^date_selection_appointment/$', appoint.date_selection_appointment, name='date_selection_appointment'),
    url(r'^get_all_services_ajax/$', service.get_all_services, name='get_all_services_ajax'),
    url(r'^save_appointment_services_ajax/$', service.save_all_services, name='save_appointment_services_ajax'),
    url(r'^get_all_advisors_ajax/$', service.get_all_advisor, name='get_all_advisors_ajax'),
    url(r'^save_advisor_ajax/$', service.save_advisor, name='save_advisor_ajax'),
    url(r'^schedule_appointment/$', appoint.schedule_appointment, name='schedule_appointment'),
    url(r'^cancel_appointment/$', appoint.cancel_appointment, name='cancel_appointment'),          
     url(r'^search_by_code_phone/$', appoint.search_by_code_phone, name='search_by_code_phone'),
     url(r'^book_appointment/$', appoint.book_appointment, name='book_appointment'),
     url(r'^check_username_exist/$', login.check_username, name='check_username'),
    url(r'^createuser/$', login.createuser, name='createuser'),
     url(r'^registeruer/$', login.registeruer, name='registeruer'),
    url(r'^sendemail/$', appoint.sendemail, name='sendemail'),
    url(r'^testingurl/$', login.testing, name='testingurl'),
     url(r'^uploadvin/$', appoint.uploadvin, name='uploadvin'),
     url(r'^book_appointment_now_new/$', appoint.book_appointment_now_new, name='book_appointment_now_new'),
     url(r'^book_appointment_now_existing/$', appoint.book_appointment_now_existing, name='book_appointment_now_ext'),
      url(r'^get_available_slabs_for_date/$', appoint.get_available_slabs_for_date, name='get_available_slabs_for_date'),
      url(r'^check_userprofile/$', appoint.check_userprofile, name='check_userprofile'),
      url(r'^get_available_adivsors_for_date/$', appoint.get_available_adivsors_for_date, name='get_available_adivsors_for_date'),
      url(r'^save_appointment_now_ext/$', appoint.save_appointment_now_ext, name='save_appointment_now_ext'),
      url(r'^statusalert/(?P<appointment_id>\d+)/$', statusalert.index, name='status_alert_index'),
      
       url(r'^approvestatus/(?P<appointment_id>\d+)/$', statusalert.approve_recomandations, name='approve_status'),
       
       url(r'^replystatus/(?P<appointment_id>\d+)/$', statusalert.reply, name='reply_status'),

        url(r'^getcart/$', cart.get_cart, name='getcart'),
    url(r'^send_activation_code/$', service.send_activation_code, name='send_activation_code'),
     url(r'^save_customer_number/$', service.save_customer_number, name='save_customer_number'),

       url(r'^paymentstatus/(?P<appointment_id>\d+)/$', statusalert.payment, name='payment_status'),
       url(r'^getcart/$', cart.get_cart, name='getcart'),
        url(r'^download_calendar/$', appoint.download_calendar, name='download_calendar'),
        url(r'^sync_gcalendar/$', login.sync_gcalendar, name='sync_gcalendar'),
  
        url(r'oauth2callback', login.auth_return, name='return'),
        url(r'print_appointment', appoint.print_appointment, name='print_appointment'),
        url(r'^service_history/(?P<vehicle_id>[a-zA-Z0-9_-]+)/?$', vehicle.service_history, name='service_history'),
         url(r'^(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.index, name='index'), 
        
   
   
]

BMW/dealership/urls.py
from django.conf.urls import url

from dealership import views

import views.login
import views.chat
from views.overview import *
from views.appointment import *
from views.customers import *
from views.rservices import *
from views.manage import *

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),    
    url(r'^$', views.login.index, name='index'),      
     url(r'delete_models', views.manage.delete_models, name='delete_models'),
    url(r'create_models', views.manage.create_models, name='create_models'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', views.login.loginview, name='login'),  
    url(r'^login/$', views.login.loginview, name='login'),
    url(r'^logout/$', views.login.logoutview, name='logout'),
    url(r'^request/$', views.login.requestview, name='request'),
    url(r'^password/change$', views.login.passchange, name='passchange'),
    url(r'^password/create$', views.login.passcreate, name='passcreate'),
    url(r'^password/reset$', views.login.passreset, name='passreset'),
    url(r'^username/reset$', views.login.userreset, name='userreset'),
    url(r'^terms/$', views.login.terms, name='terms'),
    url(r'^firstlogin/$', views.login.firstlogin, name='firstlogin'),
    #chat
    url(r'^chats/$', views.chat.chats, name='chats'),
    url(r'^chat/$', views.chat.chat, name='chat'),
    #overview
    url(r'^overview/$', views.overview.overview, name='overview'),    
    #url(r'^overview/time/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    url(r'^overview/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    #url(r'^overview/advisor/daily$', views.overview.ov_adv_daily, name='ov_adv_daily'),
    #url(r'^overview/status/daily$', views.overview.ov_status_daily, name='ov_status_daily'),
    #url(r'^overview/time/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    url(r'^overview/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    #url(r'^overview/advisor/weekly$', views.overview.ov_adv_weekly, name='ov_adv_weekly'),
    #url(r'^overview/status/weekly$', views.overview.ov_status_weekly, name='ov_status_weekly'),
    #overview_ajax
    url(r'^overview/wallboard$', views.overview.wallboard_ajax_view, name='wallboard'),
    url(r'^overview/searchcustomer$', views.overview.searchcustomer_ajax_view, name='searchcustomer'),
    url(r'^overview/time/daily/slab$', views.overview.dailyapt_ajax_view, name='ov_time_daily_slab'),
    url(r'^overview/time/daily/search$', views.overview.time_daily_search_ajax_view, name='ov_time_daily_search'),
    url(r'^overview/time/daily/appt$', views.overview.time_daily_search_appt_ajax_view, name='ov_time_daily_search_appt'),
    url(r'^overview/time/daily/row$', views.overview.appointment_row_ajax_view, name='ov_time_daily_row'),
    url(r'^overview/time/weekly/day$', views.overview.time_weekly_day_ajax_view, name='ov_time_weekly_day'),
    url(r'^overview/time/weekly/slab$', views.overview.time_weekly_slab_ajax_view, name='ov_time_weekly_slab'),
    url(r'^overview/daily/advisor$', views.overview.advisor_ajax_view, name='ov_daily_advisor'),
    url(r'^overview/daily/advisor/slab$', views.overview.advisor_daily_slab_ajax_view, name='ov_advisor_daily_slab'),
    url(r'^overview/weekly/advisor/slab$', views.overview.advisor_weekly_slab_ajax_view, name='ov_advisor_weekly_slab'),   
    url(r'^overview/daily/status$', views.overview.status_ajax_view, name='ov_daily_status'),
    url(r'^overview/daily/wayaway$', views.overview.wayaway_ajax_view, name='ov_daily_wayaway'),
    url(r'^overview/daily/status/slab$', views.overview.status_daily_slab_ajax_view, name='ov_status_daily_slab'),
    url(r'^overview/weekly/status/slab$', views.overview.status_weekly_slab_ajax_view, name='ov_status_weekly_slab'),
    url(r'^overview/appointment/detail$', views.overview.appointment_detail_ajax_view, name='ov_appointment_detail'),
    url(r'^overview/update/creaditcard$', views.overview.appointment_update_creditcard, name='ov_update_cc'),
    url(r'^overview/update/vehicle$', views.overview.appointment_update_vehicle, name='ov_update_vehicle'),
    url(r'^overview/update/insurance$', views.overview.appointment_update_insurance, name='ov_update_insurance'),
    #appointment
    url(r'^appointment/$', views.appointment.appointment, name='appointment'),  
    url(r'^appointment/create/update', views.appointment.appointment_create_update, name='appointment_create_update'), 
    url(r'^appointment/customer$', views.appointment.appointment_customer_ajax_view, name='appointment_customer'), 
    url(r'^appointment/customer/vehicle/delete$', views.appointment.customer_delete_vehicle_ajax_view, name='appointment_customer_vehicle_delete'),
    url(r'^appointment/update/time$', views.appointment.appointment_time_ajax_view, name='appointment_update_time'), 
    url(r'^appointment/wayaway$', views.appointment.appointment_wayaway_ajax_view, name='appointment_wayaway'), 
    url(r'^appointment/wayaway/save$', views.appointment.appointment_wayaway_save_ajax, name='appointment_wayaway_save'),
    url(r'^appointment/repair$', views.appointment.appointment_repair_ajax_view, name='appointment_repair'), 
    url(r'^appointment/accountinfo$', views.appointment.appointment_account_info_ajax_view, name='appointment_accountinfo'),
    url(r'^appointment/book', views.appointment.appointment_book_ajax_view, name='appointment_book'),
    url(r'^appointment/remove/service', views.appointment.appointment_remove_service, name='appointment_remove_service'),
    
    #customers
    url(r'^customers/$', views.customers.customers, name='customers'),  
    url(r'^customers/add/user$', views.customers.save_customer_ajax, name='customers_add_user'),
    url(r'^customers/add/vehicle$', views.customers.save_vehicle_ajax, name='customers_add_vehicle'),
    url(r'^customers/add/appointment$', views.customers.save_appointment_ajax, name='customers_add_appointment'),
    url(r'^customers/add/reminder', views.customers.save_guest_reminder_ajax, name='customers_add_reminder'),    
    #repair and servicea
    url(r'^rservices/$', views.rservices.rservices, name='rservices'),
    url(r'^rservices/form$', views.rservices.get_rservices_form, name='rservices_form'),
    url(r'^rservices/create/update', views.rservices.rservices_create_update, name='rservices_create_update'),  
    url(r'^rservices/delete', views.rservices.rservices_delete, name='rservices_delete'),  
    #dealership_manage
    url(r'^manage/$', views.manage.manage, name='manage'),
    url(r'^manage/deatil$', views.manage.details, name='manage_details'),
    url(r'^manage/user_term_advisor$', views.manage.add_user_advisor, name='add_user_advisor'),
    url(r'^manage/add_amenities$', views.manage.add_amenities, name='add_amenities'),
    url(r'^manage/delete_amenities$', views.manage.delete_amenities, name='delete_amenities'),
    url(r'^manage/get_resource_link$', views.manage.get_resource_link, name='get_resource_link'),
    url(r'^manage/add_resource_link$', views.manage.add_resource_link, name='add_resource_link'),
    url(r'^manage/delete_resource_link$', views.manage.delete_resource_link, name='delete_resource_link'),
    url(r'^manage/update_resource_link$', views.manage.update_resource_link, name='update_resource_link'),
    url(r'^manage/get_shopcontacts$', views.manage.get_shopcontacts, name='get_shopcontacts'),
    url(r'^manage/add_shopcontacts$', views.manage.add_shopcontacts, name='add_shopcontacts'),
    url(r'^manage/delete_shopcontacts$', views.manage.delete_shopcontacts, name='delete_shopcontacts'),
    url(r'^manage/update_shopcontacts$', views.manage.update_shopcontacts, name='update_shopcontacts'),
    url(r'^manage/get_marketing$', views.manage.get_marketing, name='get_marketing'),
    url(r'^manage/add_marketing$', views.manage.add_marketing, name='add_marketing'),
    url(r'^manage/get_feedback$', views.manage.get_feedback, name='get_feedback'),
    url(r'^manage/add_feedback$', views.manage.add_feedback, name='add_feedback'),
    url(r'^manage/get_serviceemail$', views.manage.get_serviceemail, name='get_serviceemail'),
    url(r'^manage/add_serviceemail$', views.manage.add_serviceemail, name='add_serviceemail'),
    url(r'^manage/delete_email$', views.manage.delete_email, name='delete_email'),
    url(r'^manage/update_email$', views.manage.update_email, name='update_email'),
    url(r'^manage/get_sms$', views.manage.get_sms, name='get_sms'),
    url(r'^manage/add_sms$', views.manage.add_sms, name='add_sms'),
    url(r'^manage/delete_sms$', views.manage.delete_sms, name='delete_sms'),
    url(r'^manage/update_sms$', views.manage.update_sms, name='update_sms'),
    url(r'^manage/get_shphr$', views.manage.get_shophrs, name='get_shophrs'),
    url(r'^manage/add_shphr$', views.manage.add_shophrs, name='add_shophrs'),
    url(r'^manage/delete_shphr$', views.manage.delete_shophrs, name='delete_shophrs'),
    url(r'^manage/update_shphr$', views.manage.update_shophrs, name='update_shophrs'),
    url(r'^manage/get_holidays$', views.manage.get_holidays, name='get_holidays'),
    url(r'^manage/add_holiday$', views.manage.add_holiday, name='add_holiday'),
    url(r'^manage/delete_holiday$', views.manage.delete_holiday, name='delete_holiday'),
    url(r'^manage/update_holiday$', views.manage.update_holiday, name='update_holiday'),
    url(r'^manage/get_uaform$', views.manage.get_user_advisor_form, name='get_uaform'),
    url(r'^manage/get_editviewuaform$', views.manage.get_edit_view_useradvisor, name='get_editviewuaform'),
    url(r'^manage/edituaform$', views.manage.edit_user_advisor, name='edituaform'),
    url(r'^manage/addteam$', views.manage.add_team, name='add_team'),
    url(r'^manage/editteam$', views.manage.edit_team, name='edit_team'),
    url(r'^manage/addmembers$', views.manage.add_members_team, name='add_team_members'),
    url(r'^manage/deletemembers$', views.manage.delete_members_team, name='delete_team_members'),

BMW/dealership/templates/dealership/create_models.html
{% extends 'dealership/subbase.html' %}
{% load staticfiles %}
{% block content %}
<div class="clear pad-10"></div>
<div class="container-fluid">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default" style="padding:30px;">
        	
			<form action="{% url 'customer:create_models'  %}?dealer_code={{dealer_code}}" method="post" enctype="multipart/form-data">
                                		{% csrf_token %}
                                			<div class="row">
	                                            Make: <select name="make" class="form-control">
	                                            	{%for mk in make%}
	                                            		<option value="{{mk.id}}">{{mk.name}}</option>
	                                            	{%endfor%}
	                                            </select><br/>
                                            </div>
                                            <div class="row">
                                            	<div class="col-md-6">
	                                            	Model: <select name="model" class="form-control">
	                                           		 {%for md in model%}
	                                            		<option value="{{md.id}}">{{md.name}}</option>
	                                            	{%endfor%}
	                                            	</select>
	                                            </div>
	                                            <div class="col-md-6">
	                                            	Model Name:
	                                             	<input type="text" name="model_text" value="" class="form-control"/>
	                                             </div>
                                            </div>
                                           
                                            <div class="row">
                                            Year: <select name="year" multiple="true" class="form-control">
                                            	 {%for yr in year%}
                                            		<option value="{{yr.id}}">{{yr.name}}</option>
                                            	{%endfor%}
                                            
                                            </select><br/>
                                            
                                            </div>
                                            <div class="row">
                                            	<input id="id_image" type="file" class="" name="image">
                                            </div>
                                            <input type="submit" name="submit" value="Submit" class="button"/>
    </form>
    </div>
   </div>
  </div>
    
{%endblock%}

BMW/dealership/templates/dealership/delete_models.html
{% extends 'dealership/subbase.html' %}
{% load staticfiles %}
{% block content %}
<div class="clear pad-10"></div>
<div class="container-fluid">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    	
        <div class="panel panel-default" style="padding:30px;">
        <h4>Select Year
		        <select id="select_year" name="year">
		    	{%for y in years%}
		    			
		    			<option value="{{y.name}}"
		    			{%if year.strip == y.name.strip %}
		    				selected="selected"
		    			{%endif%}
		    			>{{y.name}}</option>
		    	{%endfor%}
		    	</select>
        
        </h4> 
	<form action="{% url 'customer:delete_models'  %}?dealer_code={{dealer_code}}&year={{year}}" method="post">
                                		{% csrf_token %}
                                            {%for dvehicle in dvs%}
                                            		
                                            		<h4>
                                            			<input type="checkbox" name="models" value="{{dvehicle.id}}">
                                            			{{dvehicle.vehicle.model.name}}--{{dvehicle.vehicle.year.name}}
                                            		</h4>
                                            {%endfor%}
                                           
                                            <input type="submit" name="submit" value="Submit"/>
    </form>
    </div>
   </div>
  </div>
  <script>
  $(document).ready(function(){
	  $("#select_year").change(function(){
		  window.location="{% url 'dealership:delete_models'  %}?dealer_code={{dealer_code}}&year="+$(this).val();
		  
	  })
	  
  })
  </script>
{%endblock%}

BMW/dealership/templates/dealership/subbase.html
{% extends 'dealership/base.html' %}
{% load staticfiles %}
{% load dealership_tag %}
{% load dealership_detail %}
{% block mainheader %}
<header>
	<div class="page-header">
        <div class="container-fluid">
        	<div class="row">
            	<div class="col-sm-6">
                	
                <h1> {% dealer_detail_dealer config.dealer_code %} </h1>
                </div>
                <div class="col-sm-6 mt-10">
                	<div class="dropdown pull-right">
                        <span class="simple-menu dropdown-toggle" id="da" data-toggle="dropdown" aria-haspopup="true" 
                        aria-expanded="true">&nbsp;</span>
                        <ul class="dropdown-menu text-left" aria-labelledby="da">
                            <li><a href="{% url 'dealership:index' %}">{{config.dealer_name}}</a></li>
                            <li><a target="_blank" href="{% url 'customer:index' %}?dealer_code={{config.dealer_code}}">Launch Customer Portal</a></li>
                            <li><a target="_blank" href="{% url 'flagging:index' %}?dealer_code={{config.dealer_code}}">Launch Tracker Portal</a></li>
                            <li><a target="_blank" href="{% url 'mobilecheckin:index' %}?dealer_code={{config.dealer_code}}">Launch Check-In Portal</a></li>
                        </ul>
                    </div>
                	<div class="dropdown pull-right mr-20 mt-10 text_14">
                        <a href="#" class="dropdown-toggle text_grey" id="login" data-toggle="dropdown" aria-haspopup="true" 
                        aria-expanded="true">Hi ({{config.username}}) <i class="fa fa-chevron-circle-down text_blck"></i></a>
                        <ul class="dropdown-menu" aria-labelledby="lo{% load staticfiles %}gin">
                            <li><a href="{% url 'dealership:passchange' %}?dealer_code={{config.dealer_code}}">Change Password</a></li>
                            <li><a href="#">View Profile</a></li>
                            <li><a href="{% url 'dealership:logout' %}">Log out</a></li>
                        </ul>
                    </div>                    
                </div>
            </div>
        </div>		
    </div>
</header>
<div class="clear"></div>
{% endblock %}
	
{% block main %}
	{% block breadcrumbs %}
		{% include "dealership/app/breadcrumb.html" %}  
	{% endblock %}
	
	{% block tabs %}
		{% include "dealership/app/navbar.html" %} 
		{% include "dealership/app/partials/favorites-modal.html" %} 
	{% endblock %}
	
	{% block content %}		
	{% endblock %}
	
	{% block dropdown-menu %}
		{% include "dealership/app/dropdown-menu.html" %}
	{% endblock %}
{% endblock %}

{% block script %}
	{{ block.super }}
	<script>
		var url_ov_time_daily_slab = "{% url 'dealership:ov_time_daily_slab' %}";
		var url_ov_time_weekly_day = "{% url 'dealership:ov_time_weekly_day' %}";
		var url_ov_time_weekly_slab = "{% url 'dealership:ov_time_weekly_slab' %}";
		var url_ov_appointment_detail = "{% url 'dealership:ov_appointment_detail' %}";
		var url_ov_advisor = "{% url 'dealership:ov_daily_advisor' %}";
		var url_ov_status = "{% url 'dealership:ov_daily_status' %}";
		var url_ov_advisor_daily_slab = "{% url 'dealership:ov_advisor_daily_slab' %}";
		var url_ov_status_daily_slab = "{% url 'dealership:ov_status_daily_slab' %}";
		var url_ov_advisor_weekly_slab = "{% url 'dealership:ov_advisor_weekly_slab' %}";
		var url_ov_status_weekly_slab = "{% url 'dealership:ov_status_weekly_slab' %}";
		var url_ov_time_daily_search = "{% url 'dealership:ov_time_daily_search' %}";
		var url_ov_time_daily_search_appt = "{% url 'dealership:ov_time_daily_search_appt' %}";
		var url_appointment_create_update = "{% url 'dealership:appointment_create_update' %}";
		var url_appointment_customer = "{% url 'dealership:appointment_customer' %}";
		var url_appt_cust_veh_del = "{% url 'dealership:appointment_customer_vehicle_delete' %}";
		var url_appt_update_time_template = "{% url 'dealership:appointment_update_time' %}";
		var url_appointment_services = "{% url 'dealership:appointment_repair'%}";
		var url_appointment_wayaway = "{% url 'dealership:appointment_wayaway'%}";
		var url_appointment_wayaway_save = "{% url 'dealership:appointment_wayaway_save'%}";
		var url_appointment_account_info = "{% url 'dealership:appointment_accountinfo'%}";
		var url_get_all_services =  "{% url 'customer:get_all_services_ajax'%}";
		var url_rservices_create_update = "{% url 'dealership:rservices_create_update' %}";
		var url_rservices_delete = "{% url 'dealership:rservices_delete' %}";
		var url_get_all_advisors_ajax = "{% url 'customer:get_all_advisors_ajax'%}";
		var url_save_advisor_ajax = "{% url 'customer:save_advisor_ajax'%}";
		var url_appointment = "{% url 'dealership:appointment'%}";
		var url_overview = "{% url 'dealership:overview'%}";
		var url_ov_update_cc = "{% url 'dealership:ov_update_cc'%}";
        var url_ov_update_vehicle = "{% url 'dealership:ov_update_vehicle'%}";
        var url_ov_update_insurance = "{% url 'dealership:ov_update_insurance'%}";
		var url_customers_add_user = "{% url 'dealership:customers_add_user'%}";
		var url_customers_add_vehicle = "{% url 'dealership:customers_add_vehicle'%}";
		var url_customers_add_appointment = "{% url 'dealership:customers_add_appointment'%}";
		var url_customers_add_reminder = "{% url 'dealership:customers_add_reminder'%}";
		var url_customers_save_appointment_services = "{% url 'customer:save_appointment_services_ajax'%}";
		var url_appointment_book = "{% url 'dealership:appointment_book'%}";
		var url_ov_time_wallboard = "{% url 'dealership:wallboard' %}";
	
	    var get_available_slabs_for_date = "{% url 'customer:get_available_slabs_for_date'%}";
	    
	    var get_all_favorites = "{% url 'dealership:all_favorites'%}";
	    var get_dealer_favorites = "{% url 'dealership:dealer_favorites'%}";
	    var save_dealer_favorites = "{% url 'dealership:save_dealer_favorites'%}";
	    
	    var url_rservices_form = "{% url 'dealership:rservices_form'%}";
        
        var url_remove_service = "{% url 'dealership:appointment_remove_service'%}";
		var url_customer_edit = "{% url 'dealership:edit_customer'%}";
		$(document).ready(function() {	
			var dealershipbase = new Dealership();
			
			$(".{{config.tab}}").addClass("active");
			
			
			
			$(".dropdown-hover").hover(            
			function() {
				$('.dropdown-menu', this).stop( true, true ).fadeIn("fast");
				$(this).toggleClass('open');
				$('b', this).toggleClass("caret caret-up");                
			},
			function() {
				$('.dropdown-menu', this).stop( true, true ).fadeOut("fast");
				$(this).toggleClass('open');
				$('b', this).toggleClass("caret caret-up");                
			});  
			
			$(document.body).on('click', '.panel-title a', function(event) {		
				if($(this).children('.fa').hasClass("fa-plus-circle")){
					$(this).children('.fa').removeClass("fa-plus-circle").addClass('fa-minus-circle');
				}
				else{
					$(this).children('.fa').removeClass("fa-minus-circle").addClass('fa-plus-circle');
				}
			}); 
			
			$('#add-fav-link').click(function(){
				dealershipbase.getGetDataFromServer(get_all_favorites, {}, loadAllFavorites);				
			});
			
			$('#add-fav-button').click(function(){				
				data={'favorites_id':$('#favorites-modal-list').val()};
				dealershipbase.getTemplateFromServer(save_dealer_favorites, data, saveFavoritesCallback);				
			});

			
		});		
		
		function loadAllFavorites(data)
		{
			console.info(data);
			$('#favorites-modal-list').html("<option>Add Favorites</option>");
			for(i in data["favorites"]){
				$('#favorites-modal-list').append("<option value="+data["favorites"][i]["id"]+">"+data["favorites"][i]["name"]+"</option>");
			}
			$('#add-favorites-modal').modal('show');
		}
		
		function saveFavoritesCallback(content)
		{
			$('.navbar .submenu').html(content);
			$('#add-favorites-modal').modal('hide');
		}
	</script>
{% endblock %}