BMW/BMW/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^dealership/', include('dealership.urls', namespace="dealership")),
    url(r'^dealership/', include('dealership.urls', namespace='dealership' , app_name='dealership')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^flagger/', include('flagging.urls', namespace='flagging')),
    url(r'^mobilecheckin/', include('mobilecheckin.urls', namespace='mobilecheckin' , app_name='mobilecheckin')),
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^subview', include('subview.urls')),

# url(r'^oauth2/', include('oauth2_authentication.urls', namespace="oauth2"))
    
)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

BMW/customer/urls.py
from django.conf.urls import url

from customer.views import login, main, vehicle, account, notifications, appoint, service , statusalert,cart


urlpatterns = [  
    url(r'^$', login.login, name='index'),
#     url(r'^import_csv$', login.import_csv, name='index'),
    url(r'pull_models', login.pull_models, name='pull_models'),
    url(r'create_models', login.create_models, name='create_models'),
    url(r'delete_models', login.delete_models, name='delete_models'),
    url(r'create_models', login.create_models, name='create_models'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.login, name='login'),
    url(r'^login/?$', login.login, name='login'),
    url(r'^password/reset/$', login.passreset, name='passreset'),
    url(r'^username/reset/$', login.userreset, name='userreset'),
    url(r'^password/create$', login.passcreate, name='passcreate'),
    url(r'^main/$', vehicle.mainview , name='main'),
    url(r'^accountsettings/$', account.accountview , name='accountsettings'),
    url(r'^logout/$', login.logout, name='logout'),
    url(r'^test_ocr/$', main.test_ocr, name='test_ocr'),
    url(r'^puller/$', main.test_puller, name='puller'),
    url(r'^vehichlewidget/$', vehicle.get_vehicle, name='vehichlewidget'),
    url(r'^delete_vehicle/$', vehicle.del_vehicle, name='del_vehicle'),
    url(r'^ocr_snap/$', vehicle.ocr_snap, name='ocr_snap'),
    url(r'^delete_account/$', account.delete, name='delete_account'),
    url(r'^notifications/$', notifications.notificationssettings, name='notifications'),
    url(r'^findapp/$', appoint.find_exiting_appointment, name='findapp'),
    url(r'^search_app/$', appoint.search_app, name='search_app'),#used for searching thourhg ajax
    url(r'^new_customer_vehicle/$', login.new_customer_vehicle, name='new_customer_vehicle'),
    url(r'^vehicle_selection_appointment/$', appoint.vehicle_selection, name='vehicle_selection_appointment'),
    url(r'^service_selection_appointment/$', appoint.service_selection_appointment, name='service_selection_appointment'),
    url(r'^date_selection_appointment/$', appoint.date_selection_appointment, name='date_selection_appointment'),
    url(r'^get_all_services_ajax/$', service.get_all_services, name='get_all_services_ajax'),
    url(r'^save_appointment_services_ajax/$', service.save_all_services, name='save_appointment_services_ajax'),
    url(r'^get_all_advisors_ajax/$', service.get_all_advisor, name='get_all_advisors_ajax'),
    url(r'^save_advisor_ajax/$', service.save_advisor, name='save_advisor_ajax'),
    url(r'^schedule_appointment/$', appoint.schedule_appointment, name='schedule_appointment'),
    url(r'^cancel_appointment/$', appoint.cancel_appointment, name='cancel_appointment'),          
     url(r'^search_by_code_phone/$', appoint.search_by_code_phone, name='search_by_code_phone'),
     url(r'^book_appointment/$', appoint.book_appointment, name='book_appointment'),
     url(r'^check_username_exist/$', login.check_username, name='check_username'),
    url(r'^createuser/$', login.createuser, name='createuser'),
     url(r'^registeruer/$', login.registeruer, name='registeruer'),
    url(r'^sendemail/$', appoint.sendemail, name='sendemail'),
    url(r'^testingurl/$', login.testing, name='testingurl'),
     url(r'^uploadvin/$', appoint.uploadvin, name='uploadvin'),
     url(r'^book_appointment_now_new/$', appoint.book_appointment_now_new, name='book_appointment_now_new'),
     url(r'^book_appointment_now_existing/$', appoint.book_appointment_now_existing, name='book_appointment_now_ext'),
      url(r'^get_available_slabs_for_date/$', appoint.get_available_slabs_for_date, name='get_available_slabs_for_date'),
      url(r'^check_userprofile/$', appoint.check_userprofile, name='check_userprofile'),
      url(r'^get_available_adivsors_for_date/$', appoint.get_available_adivsors_for_date, name='get_available_adivsors_for_date'),
      url(r'^save_appointment_now_ext/$', appoint.save_appointment_now_ext, name='save_appointment_now_ext'),
      url(r'^statusalert/(?P<appointment_id>\d+)/$', statusalert.index, name='status_alert_index'),
      
       url(r'^approvestatus/(?P<appointment_id>\d+)/$', statusalert.approve_recomandations, name='approve_status'),
       
       url(r'^replystatus/(?P<appointment_id>\d+)/$', statusalert.reply, name='reply_status'),

        url(r'^getcart/$', cart.get_cart, name='getcart'),
    url(r'^send_activation_code/$', service.send_activation_code, name='send_activation_code'),
     url(r'^save_customer_number/$', service.save_customer_number, name='save_customer_number'),

       url(r'^paymentstatus/(?P<appointment_id>\d+)/$', statusalert.payment, name='payment_status'),
       url(r'^getcart/$', cart.get_cart, name='getcart'),
        url(r'^download_calendar/$', appoint.download_calendar, name='download_calendar'),
        url(r'^sync_gcalendar/$', login.sync_gcalendar, name='sync_gcalendar'),
  
        url(r'oauth2callback', login.auth_return, name='return'),
        url(r'print_appointment', appoint.print_appointment, name='print_appointment'),
        url(r'^service_history/(?P<vehicle_id>[a-zA-Z0-9_-]+)/?$', vehicle.service_history, name='service_history'),
         url(r'^(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.index, name='index'), 
        
   
   
]

BMW/customer/views/account.py
import os

from PIL import Image
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http.response import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
import pytesseract

from customer.app_confg import confg
from customer.decorators.decorators import customer_group_check
from customer.forms import CustomerVehichleForm, CustomerAccountForm, \
    CustomerInsuranceForm, CreditDebitForm

from dealership.forms import ChangePasswordForm

from customer.factories import CustomerServicesFactory
import json as mainjson
from livechat.forms import UploadForm


@user_passes_test(customer_group_check,login_url=confg.REDIRECT_URL)
def delete(request):
        try:
            customer_factory = CustomerServicesFactory()
            user = request.user
            service = customer_factory.get_instance("account")#AccountService()
            resp = service.delete_account(user.userprofile)
            if resp:
                messages.success(request, "Account Deleted Successfully")
            else:
                messages.success(request, "Unable to Delete Account")
        except:
            messages.error(request, "Unable to  Deleted account. Try later")
        return HttpResponseRedirect(reverse("customer:accountsettings"))
    
    
@user_passes_test(customer_group_check,login_url=confg.REDIRECT_URL)     
def accountview(request):
    """
            This is the account view where oyu can sae the account information
    """
    customer_factory = CustomerServicesFactory()
    user = request.user
    dealer_code = request.session["dealer_code"]
    account_service =  customer_factory.get_instance("account")
    service = customer_factory.get_instance("user")
    template_name = 'customer/customer_account.html'
    name = request.user.first_name+" "+request.user.last_name
    userprofile =service.get_userprofile(request.user)
    insurance_profile = service.get_user_driver_insurance(userprofile)
    cc_profile = service.get_cc_profile(userprofile)
    account_initial = account_service.get_initial_user_form(user, userprofile)
    driver_initial  =account_service.get_initial_driver_form(user, insurance_profile,userprofile)
    cc_initial = account_service.get_initial_cc_form(user,cc_profile,userprofile)
    customer_form =CustomerAccountForm(instance=userprofile,initial=account_initial)
    driver_form = CustomerInsuranceForm(instance=insurance_profile,initial=driver_initial)
    cc_form = CreditDebitForm(instance=cc_profile,initial=cc_initial)
    pass_form = ChangePasswordForm() 
    tab = "account"
    
    if request.method == 'POST':
        resp = False
        password_changed=False
        
        if request.POST.get("type") == "account":
            
            customer_form = CustomerAccountForm(request.POST,instance=userprofile)
            resp = account_service.save_account_form(user,userprofile,customer_form,account_initial)
            msg = "Account Information saved  successfully" #
            
        elif request.POST.get("type")=="driver":
            driver_form = CustomerInsuranceForm(request.POST,instance = insurance_profile)
            resp = account_service.save_driver_form(insurance_profile,driver_form)
            msg = "Driver Liscense and Insurance Information saved  successfully"
            
        elif request.POST.get("type")=="cc":
            cc_form = CreditDebitForm(request.POST,instance = cc_profile)
            resp = account_service.save_cc_form(cc_profile,cc_form)
            msg =  "Debit/Credit form save successfully"
            
        elif request.POST.get("type")=="change_password":
            pass_form = ChangePasswordForm(request.POST)    
            resp = account_service.save_password_form(pass_form,user)    
            msg =  "Password Changed successfully"
            password_changed = True
        if password_changed:
            messages.success(request, msg)
            return  HttpResponseRedirect(reverse("customer:index")+"?dealer_code="+dealer_code)
        elif resp:
            messages.success(request, msg)
            return  HttpResponseRedirect(reverse("customer:accountsettings"))
        
            
    else:
        customer_form = CustomerAccountForm(instance=userprofile,initial=account_initial)
        driver_form = CustomerInsuranceForm(instance=insurance_profile,initial=driver_initial)
        cc_form = CreditDebitForm(instance=cc_profile,initial=cc_initial)
        pass_form = ChangePasswordForm() 
        
    
    context = {"page_title":"Customer Profile","tab":tab,
                                          "customer_form":customer_form,
                                          "driver_form":driver_form,
                                          "cc_form":cc_form,
                                          "pass_form":pass_form,
                                         "dealer_code":dealer_code,
                                          'acitve' : True,
                                          }
    service.set_centrifuge_context(request,dealer_code,userprofile, context,chatposition="top")
    return render(request, template_name,context)
    
    
    
    

#     return CustomerAccountForm(initial=initial,instance=userprofile) 
      
    
                  
    

BMW/customer/views/cart.py
import datetime

from PIL import Image
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render
from django.shortcuts import render
from django.utils import timezone

from BMW import settings
from customer.app_confg import confg
from customer.decorators.decorators import dealership_required, dealership_required_or_logged_in, \
    appointment_required, customer_group_check
from customer.factories import CustomerServicesFactory
from customer.forms import CustomerVehichleForm, CustomerAccountForm, \
    GuestccountForm, UploadVinForm
from dealership.factories import DealerShipServicesFactory
from dealership.forms import LoginForm, CreateUserForm
from dealership.models import CustomerVehicle, UserProfile, Appointment
import json as mainjson


@appointment_required
@dealership_required_or_logged_in
def get_cart(request,dealer_code,profile,appointment):
    try:
        if appointment:
                
                customer_factory = CustomerServicesFactory()
                dealer_factory = DealerShipServicesFactory()
                dealer_service = dealer_factory.get_instance("dealership")
                dealer = dealer_service.get_dealer_by(dealer_code)
                userservice = customer_factory.get_instance("user")
                appointmentservice = dealer_factory.get_instance("appointment")
                repairservice = dealer_factory.get_instance("repair")
                services = repairservice.get_service_for(appointment.id,'s')
                repairs = repairservice.get_service_for(appointment.id,'r')
                print services
                print repairs
               
                context = {
                                        "mainurl":settings.MEDIA_ROOT,
                                          "appointment":appointment,
                                          "dealer_code":dealer_code,
                                          "services":services,"repairs":repairs,
                                          "cart_count":len(repairs)+len(services)
            
                }
   
                return render(request, "customer/cart/main.html",context)
        else:
#             return ""
            return render(request, "customer/cart/main.html",{})
    except Exception,e:
        print e
            

BMW/customer/views/paypal_execute.py
import paypalrestsdk
import logging
logging.basicConfig(level=logging.INFO)

# ID of the payment. This ID is provided when creating payment.
payment = paypalrestsdk.Payment.find("PAY-28103131SP722473WKFD7VGQ")

# PayerID is required to approve the payment.
if payment.execute({"payer_id": "DUFRQ8GWYMJXC"}):  # return True or False
    print("Payment[%s] execute successfully" % (payment.id))
else:
    print(payment.error)

BMW/mobilecheckin/views/appointments.py
'''
Created on Nov 28, 2015

@author: aroofi
'''
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.http import JsonResponse
from django.shortcuts import render

from customer.factories import CustomerServicesFactory
from customer.forms import GuestccountForm
from dealership.decorators import *
from dealership.factories import DealerShipServicesFactory
from dealership.services.appointmentservices import AppointmentService
from dealership.services.repairservices import RepairService
import json as mainjson
from mobilecheckin import confg
from mobilecheckin.decorators import *
from mobilecheckin.forms import WalkinForm


# Create your views here.
appointments_template = 'mobilecheckin/appointments/'
base_template = 'mobilecheckin/'

@checkin_access_check
def index(request):
    """
    Index
    *main page after dealer logged in
    """
    customer_factory = CustomerServicesFactory()
    dealer_factory = DealerShipServicesFactory()
    service = dealer_factory.get_instance("vehicle")#Vehicl
#     vehichles = service.get_vehichles()
    
#     dealer_service = dealer_factory.get_instance("dealership")
    dealer_service = dealer_factory.get_instance("dealership")
    vehicle_service = dealer_factory.get_instance("vehicle")
    dealer = dealer_service.get_dealer_by(request.session.get("dealer_code"))
    vehichles = service.get_vehichles_dealer(dealer)
    walkin = GuestccountForm()
    aptservice = AppointmentService()
    status = aptservice.get_appointments_status()
    wayaway = aptservice.get_wayaway()
    template_name = appointments_template+'index.html'
    vehicles = list(vehichles)
    config = {"dealer_id":request.session["dealer_id"],
              "dealer_code":request.session["dealer_code"],
              "CENTRIFUGE_URL":settings.CENTRIFUGE_URL,
              "CENTRIFUGE_SECRET":settings.CENTRIFUGE_SECRET}
    
    
    return render(request, template_name, {'config':config, "vehicles":mainjson.dumps(vehicles),
                                           
                                           'status':status['data'], 'wayaway':wayaway['data'], 'walkinform' :walkin, 'dealer_code':request.session["dealer_code"]})

@checkin_access_check
def appointment_update(request):
    context = {}
    if request.method == 'POST': 
        data = {}
        for key, value in request.POST.iteritems():
            data[key] = value
        aptservice = AppointmentService()
        context = aptservice.update_appointment(data)  
    return JsonResponse(context)
@checkin_access_check
def remove_service(request):
    context={}
    if request.method == 'POST':
        id =  request.POST.get('id')
        rs = RepairService()
        context['deleted'] = rs.remove_service(id)
        
    return JsonResponse(context)
        

BMW/customer/templates/customer/appointment/partials/advisor_selection.html
    {% load staticfiles i18n %}
    
    	<div class="panel panel-default collaps_main_container" id="advisor_selection_from">
				            <div class="panel-heading wht-heading" role="tab" >
				                <h6 class="panel-title">
				                    <a  role="button "  aria-expanded="false" aria-controls="service">
				                    	<span class="collapse_button_trigger pointer">Select an Advisor</span> 
				                    	<i class="fa fa-minus-circle text_blue pull-right collapse_button" data-minclass="fa-minus-circle" data-plusclass="fa-plus-circle"></i>
				                    </a>
				                </h6>
				            </div>
				            <div id="service" class=" collapsable_div" role="tabpanel" aria-labelledby="service">
				                <div class="panel-body">
				                	     
				                    <div class="clear pad-10"></div>
				                    
				                   <div class="row" id="advisor-appointment" >
				                   		
									</div>
									<nav class="text-center"> 
					     			   <ul id="advisor_pagination" class="pagination">
					     			   </ul>
			     					</nav>
				
				                </div>
				            </div>
				             
				 </div>
<!--     <div class="well collaps_main_container">
			                	<h5 class="mt-0">
			                			<a href="#" class="text_blck">
			                			<i class="fa fa-minus-square-o fa-lg mr-10 collapse_button"></i></a> Advisor
			                	</h5>
								<div class="collapsable_div">
									<div class="row" id="advisor-appointment">
									</div>
									<nav class="text-center"> 
					     			   <ul id="advisor_pagination" class="pagination">
					     			   </ul>
			     					</nav>
								</div>   
			         	
     			 	  </div> -->
     <script src="{% static "customer/js/advisor_selection.js" %}"></script>
    <script type="text/javascript">
    
    	$('document').ready(function(){
    		
    		
    	});
    </script>

BMW/customer/templates/customer/appointment/partials/appointment_list_new.html
{% load staticfiles %}
					{% if forloop.counter0|divisibleby:2 %}
		        		</div>
		        		<div class="row">
		        	{%endif%}
<div class="col-sm-6" id="main_appointment_{{tmpappointment.id}}" style="padding-bottom:20px">
        	<div class="bg_wht pad-15">
            	<h4 class="well well-sm mt-0">Your Appointment For {{tmpappointment.vehicle.vehicle.make.name}}/{{tmpappointment.vehicle.vehicle.model.name}}/{{tmpappointment.vehicle.vehicle.year.name}}</h4>
                <div class="row">
                	<div class="col-xs-7 text_14">
                    	<p>{{tmpappointment.start_time|date:'l F d, Y,h:ia' }}</p>
                        {%if appointment.way_away%}
                        	<p>A WAY AWAY: {{appointment.way_away.name}}</p>
                        {%endif%}
                    </div>
                    <div class="col-xs-5">
                    	<div class="media">
                        	
  							<div class="media-body">
                            	{%if tmpappointment.advisor %}
								                                    	<div class="media-left">
								                                        	<a href="#">
								                                        			{%if tmpappointment.advisor.userprofile.avatar  %}
								                                        				<img src="{{tmpappointment.advisor.userprofile.avatar.url}}" width="75" class="media-object img-thumbnail">
								                                        			{%else%}
								                                        				<img src="{%static 'images/noimage.gif' %}"  width="75" class="media-object img-thumbnail">
								                                        			{%endif%}
								                                        	</a>
								                                        </div>
									                                        <div class="media-body">
									                                        	<p>Advisor:<br>{{tmpappointment.advisor.userprofile.first_name}} {{tmpappointment.advisor.userprofile.last_name}}</p>
									                                            <a  class=" pointer btn btn-info btn-xs pull-right advisor_selector" data-toggle="modal" data-target="#confirm-edit-advisor" data-appointment = {{tmpappointment.id}} data-advisor = "{{tmpappointment.advisor.id}}" >Edit</a>
									                                        </div> 
									                         {%else%}
									                         			<div class="media-left">
								                                        	<a href="#">
								                                        			<img src="{%static 'images/noimage.gif' %}"  width="75" class="media-object img-thumbnail">
								                                        	</a>
								                                        </div> 
								                                       
									                                       <div class="media-body">
									                                        	<p>Advisor:<br>None</p>
									                                            <a  class=" pointer btn btn-info btn-xs pull-right advisor_selector" data-toggle="modal" data-target="#confirm-edit-advisor" data-appointment = {{tmpappointment.id}} data-advisor = {{tmpappointment.advisor.id}}>Add</a>
									                                        </div> 
							                             {%endif%}  
  							</div>
						</div>
                    </div>
                </div>
                <div class="clear pad-10"></div>
                <h4 class="well well-sm">Service Scheduled</h4>
                <div class="row">
                	<div class="col-xs-6 text_14">
                		<p>
                			{%for service in tmpappointment.appointmentservice.all %}
                				{{service.service.name}}</br>		
                			{%endfor%}
                    	</p>
                    </div>
                    <div class="col-xs-6">
                    	<div class="media">
                        	<div class="media-left">
                        				<a href="#">
                        	
                        					<img src="{{tmpappointment.vehicle.vehicle.mainimage.url}}" width="100">
                        				</a>
                        	</div>
  							<div class="media-body">
                            	<p><strong>{{tmpappointment.vehicle.vehicle.make.name}}</strong></p>
                                 <p>
                                    	Make: &nbsp; {{tmpappointment.vehicle.vehicle.make.name}}<br>
                                        Model: &nbsp;  {{tmpappointment.vehicle.vehicle.model.name}}<br>
                                        
                                  </p>
  							</div>
						</div>
                    </div>
                </div>
                <div class="clear pad-10"></div>
                <h4 class="well well-sm">Confirm Code: {{tmpappointment.confirmation_code}}</h4>
                <div class="row">
                	{%if tmpappointment  %}
                            	<div class="col-xs-6">
                                	<a href="{%url 'customer:search_by_code_phone'%}?dealer_code={{dealer_code}}&appointment_id={{tmpappointment.id}}&profile_id={{request.GET.profile_id}}&code={{request.GET.code}}" class="btn btn-default  btn-block " id="select_appt_btn_{{tmpappointment.id}}">Edit appointment</a>
                                </div>
                                <div class="col-xs-6">
                                	<a data-href="{%url 'customer:cancel_appointment'%}?dealer_code={{dealer_code}}&appointment_id={{tmpappointment.id}}&profile_id={{tmpappointment.customer.id}}&dealer_code={{dealer_code}}&referer={{ request.get_full_path|urlencode }}" id="cancel_appt_btn_{{tmpappointment.id}}" class="btn btn-danger btn-block " data-toggle="modal" data-target="#confirm-cancel-appointment">Cancel appointment</a>
                                </div>
		                                      
		                            
		             {%endif%}
                </div>
                <div class="pad-20"></div>
                <p class="text_14">
                	Sync to your calender &nbsp; 
                	<a href="{%url 'customer:sync_gcalendar'%}?appointment_id={{tmpappointment.id}}&refferrer={{ request.get_full_path|urlencode }}" title="Sync to Google">
                		<i class="fa fa-calendar fa-lg"></i></a> 
                	&nbsp; 
                    <a href="{%url 'customer:download_calendar'%}?appointment_id={{tmpappointment.id}}" class="text_blck" title="Add to your Calendar">
                    	<i class="fa fa-file-archive-o fa-lg"></i>
                    </a> &nbsp; 
                    <!--  <a href="#"><i class="fa fa-calendar-plus-o fa-lg"></i></a>-->
                    <a target="__blank" href="{%url 'customer:print_appointment'%}?appointment_id={{tmpappointment.id}}" class="btn btn-info pull-right btn-sm">Print</a>
                </p>
            </div>
        </div>    
        
        <script>
        	{%if appointment and tmpappointment.id == appointment.id%}
        		$("#select_appt_btn_{{tmpappointment.id}}").prop("href","#");
        		$("#cancel_appt_btn_{{tmpappointment.id}}").prop("href","#");
        		$("#main_appointment_{{tmpappointment.id}}").css("opacity","0.4");
        		$("#main_appointment_{{tmpappointment.id}}").find("button").prop("disable","disabled")
        		$("#main_appointment_{{tmpappointment.id}}").find("a").prop("a","#")
        	{%endif%}
        	
        	
        </script>       

BMW/customer/templates/customer/appointment/partials/appointment_tabs.html
{%if appointment %}
	<ul id="myTabs" class="service_menu "> 
	        	<li role="dropdown" class="dropdown dropdown-hover {% if tab == '' %} active {%endif%}">
		            	<a href="{% url 'customer:vehicle_selection_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}" id="vehicles-tab">Vehicles</a>
		            	<ul class="dropdown-menu" style="display: none;width:100%">
		           			 <li>
		           			 		{%if appointment.vehicle%}
		           			 			{{appointment.vehicle.vehicle.make.name}} {{appointment.vehicle.vehicle.model.name}} 
		           			 		{%else%}
		           			 			Please select a vehcile
		           			 		{%endif%}
		           			 </li>
		     		   </ul>
          		  </li> 
          		  
	            <li role="dropdown"  class="dropdown dropdown-hover {% if tab == 'service' %} active {%endif%}">
	          	  
	            	  <a href="{% url 'customer:service_selection_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}">Service and Repair </a>
	            		<ul class="dropdown-menu" style="display: none;width:100%">
		            		<li>
		            				<div id="service_repair_top_bar" >
			           			 			No Service or Repair added
			           			 	</div>
			           			 </li>
			           	</ul>
	            </li>
	            
	            <li role="dropdown" {% if tab == 'appointment' %} class="active" {%endif%}>
	            	
	            	 <a href="{% url 'customer:date_selection_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}">Appointment</a>
	            </li>
	            <li role="dropdown" {% if tab == 'book' %} class="active" {%endif%}>
	            	
	            	 <a href="{% url 'customer:book_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}">Review and Book</a>
	            </li>
	</ul>
{%endif%}
	<div class="clear pad-10"></div>

BMW/customer/templates/customer/appointment/partials/book_error.html
<div class="modal fade" id="error-appointment-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
              <h4> Information Missing</h4>
            </div>
            <div class="modal-body" >
            	<ul>
            			
	              Your appointment is not complete.
	              {% if appointment.start_time == None %}
	              <li>
					Way away information is missing 
						<a href="{% url 'customer:date_selection_appointment' %}?dealer_code={{dealer_code}}&accordion=wayaway&appointment_id={{appointment.id}}" >
						Back
						</a>
						<br/>
					</li>
	              <li>
					Date information is missing 
						<a href="{% url 'customer:date_selection_appointment' %}?dealer_code={{dealer_code}}&accordion=date&appointment_id={{appointment.id}}" >
						Back
						</a>
						<br/>
					</li>
					{%endif%}
					{% if appointment.way_away == None %}
	              
				  {%endif%}
			  
			  
		
               </ul>
            </div>
            <div class="modal-footer">
                
            </div>
        </div>
    </div>
</div>		
<script>
$(document).ready(function(){
	$('#error-appointment-modal').modal('show');
});
</script>

BMW/customer/templates/customer/appointment/partials/book_form_user.html
{%if isbooked == False %}
	<div class="col-sm-offset-10 col-sm-2">
		<form  method="POST" action="{% url 'customer:book_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}" id="form_submit_book">
				{% csrf_token %}
				 <input type="hidden" name="submitting_form"/>
				 <input type="hidden" name="dealer_code" value="{{dealer_code}}"/>      
			     <input type="hidden" name="appointment_id" value="{{appointment.id}}"/>
				<div class="text-right mt-10">
               	 	<button  style="float:right;width:70px" id="book_btn"  data-loggedin="true" class="btn btn-info">Book</button>
            	</div>
		</form>
	</div>
	
{%else%}
{%endif%}